version: '3.3'
services:

  senzing-webapp:
    image: senzing/ssl-entity-search-web-app
    container_name: senzing-webapp
    command: "start:docker"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SENZING_API_SERVER_URL: "http://senzing-api-server:8080"
      SENZING_WEB_SERVER_PORT: 8080
      SENZING_WEB_SERVER_API_PATH: '/api'
    networks:
      - sz-api-network
    volumes:
      - '/app/node_modules'
    ports:
      - 8081:8080
    restart: 'always'
    secrets:
      - source: SZ_WEBAPP_SSL_CERT
        target: server.cert
        uid: '1001'
        gid: '1001'
      - source: SZ_WEBAPP_SSL_KEY
        target: server.key
        uid: '1001'
        gid: '1001'
      - source: SZ_WEBAPP_AUTH_JSON
        target: users.json
        uid: '1001'
        gid: '1001'

networks:
  sz-api-network:

secrets:
  SZ_WEBAPP_SSL_CERT:
    file: '../CERTS/server.cert'
  SZ_WEBAPP_SSL_KEY:
    file: '../CERTS/server.key'
  SZ_WEBAPP_AUTH_JSON:
    file: '../USERS/users.json'
