version: '3'
services:

  sut:
      command: "test:docker"
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        SENZING_API_SERVER_URL: "http://senzing-api-server:8080"
        SENZING_WEB_SERVER_PORT: 8080
        SENZING_WEB_SERVER_API_PATH: '/api'
      networks:
        - sz-api-network
      volumes:
        - '.:/app'
        - '/app/node_modules'
      ports:
        - '4201:4200'
      restart: 'no'

networks:
  sz-api-network:
