name: Cron Schedule 3 hr Test Entity Search Web App Build on Debian

on:
  push:
    branches:
      - issue-92.bryan-nice
#  schedule:
#    - cron: '0 */3 * * *'

jobs:
  cronBuildEntitySearchWebApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Entity Search Web App
        id: build_entity_search_web_app
        run: |
          make \
            BASE_IMAGE="node:12.2.0" \
            docker-build >> build_failure.log 2>&1
            cat build_failure.log >> output.log 2>&1
      - name: Create Jira Issue on Build Failure
        id: create_jira_issue
        if: failure()
        run: |
          docker run --rm \
            --env JIRA_ISSUE_DESCRIPTION="The commit SHA is: _${{ github.sha }}_." \
            --env JIRA_API_TOKEN=${{ secrets.JIRA_SECRET }} \
            --env JIRA_USERNAME=${{ secrets.JIRA_USERNAME }} \
            --env JIRA_ACCOUNT_URL=${{ secrets.JIRA_ACCOUNT_URL }} \
            --env JIRA_PROJECT=PBF \
            --env JIRA_ISSUE_TYPE=Task \
            --env JIRA_ISSUE_SUMMARY="Entity Search Web App Debian build failed on GitHub SHA ${{ github.sha }}" \
            senzing/git-action-jira-issue-creation:1.0.0
      - name: Slack Notification
        id: slack_notification
        uses: Senzing/git-action-slack-notification@1.0.0
        if: failure()
        env:
          SLACK_CHANNEL: ci-cd-dev
          SLACK_COLOR: '#3278BD'
          SLACK_TITLE: 'Entity Search Web App Debian build failed on GitHub Commit SHA ${{ github.sha }}'
          SLACK_MESSAGE: |
            Failed to build on GitHub Commit SHA ${{ github.sha }}
            Git Issue URL: ${{ steps.create_jira_issue.outputs.jira_issue_url }}
          SLACK_USERNAME: senzing-api-server
          SLACK_WEBHOOK: ${{ secrets.SLACK_NOTIFICATION }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTION: ${{ github.action }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
      - name: Persisting log
        id: persisting_log
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: workflow_log
          path: output.log

